{
 "title": "Kubeless",
 "description": "Dashboard for Kubeless",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Function call rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( rate(function_calls_total[5m])) by (function)",
     "legendFormat": "function={{function}}"
    }
   ]
  },
  {
   "title": "Function failure rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( rate(function_failures_total[5m])) by (function)",
     "legendFormat": "function={{function}}"
    }
   ]
  },
  {
   "title": "Execution duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(function_duration_seconds_sum[5m])) by (function)"
    }
   ]
  }
 ]
}